### ISSUE TITLE
Production dependencies are not satified

### ISSUE THREAD

**Issue by AndresCidoncha** [mrholek/CoreUI-Vue#54]
Using the Vue_Starter package, `npm install --production` doesn't install the required dependencies.

**Steps to reproduce:**

1. Clone this repo
2. Open a terminal in the Vue_Starter folder
3. Run `npm install --production`
4. Run `npm run build`

This steps are supposed to build the web with only production dependencies (defined in dependencies section of package.json) but the last step fails.

**Logs:**

```
$ npm install --production

> bootstrap-vue@2.0.0-rc.1 postinstall /home/andrescidoncha/Documents/CoreUI-Vue/Vue_Starter/node_modules/bootstrap-vue
> opencollective postinstall || exit 0


     *** Thank you for using bootstrap-vue! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/bootstrap-vue/donate

                    ***

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

added 63 packages in 4.248s


$ npm run build

> @coreui/vue@1.0.10 build /home/andrescidoncha/Documents/CoreUI-Vue/Vue_Starter
> node build/build.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/andrescidoncha/Documents/CoreUI-Vue/Vue_Starter/build/check-versions.js:1:75)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @coreui/vue@1.0.10 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @coreui/vue@1.0.10 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/andrescidoncha/.npm/_logs/2018-02-07T10_01_46_293Z-debug.log
```

**Comment by xidedix** [comment]
There must be some kind of misunderstanding. It doesn't work that way.
`devDependencies` are necessary to run `build` scripts.

**Comment by AndresCidoncha** [comment]
Maybe I misunderstand the concept of the `--production` flag... But if devDependencies are used to build the final product, what's the point of calling this flag `--production`?

Sorry about the no-issue 🙏

**Comment by xidedix** [comment]
We don't use `--production` flag. Probably other build systems do.
